language: r
warnings_are_errors: true
sudo: required
apt_packages:
  - libgsl0-dev
r_binary_packages:
  - numDeriv
  - expm
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'